[project]
name = "ai-research-buddy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Assar", email = "assarlannerbornzz@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ai-research-buddy = "ai_research_buddy:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
